# Generated by Django 6.0.7 on 2026-07-24 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CerereConcediu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_concediu', models.CharField(choices=[('odihna', 'Concediu de Odihnă'), ('medical', 'Concediu Medical'), ('fara_plata', 'Concediu Fără Plată')], default='odihna', max_length=20)),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('motiv', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_asteptare', 'În Așteptare'), ('aprobat', 'Aprobat'), ('respins', 'Respins')], default='in_asteptare', max_length=20)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cereri_concediu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAngajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('fisier', models.FileField(upload_to='documente_angajati/')),
                ('data_incarcare', models.DateTimeField(auto_now_add=True)),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pontaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_intrare', models.TimeField(blank=True, null=True)),
                ('ora_iesire', models.TimeField(blank=True, null=True)),
                ('ore_lucrate', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontaje', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAngajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functia', models.CharField(max_length=100, verbose_name='Funcție')),
                ('departament', models.CharField(max_length=100, verbose_name='Departament')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('data_angajare', models.DateField(blank=True, null=True, verbose_name='Data Angajării')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
