# Generated by Django 6.0.7 on 2026-07-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetariAplicatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_24h', models.BooleanField(default=True, verbose_name='Folosește formatul de 24 de ore')),
                ('nume_companie', models.CharField(default='Panou HR', max_length=100, verbose_name='Nume Companie')),
            ],
        ),
    ]
