# Generated by Django 6.0.7 on 2026-07-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setariaplicatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontaj',
            name='km_plecare',
            field=models.PositiveIntegerField(default=0, verbose_name='KM Plecare'),
        ),
        migrations.AddField(
            model_name='pontaj',
            name='km_sosire',
            field=models.PositiveIntegerField(default=0, verbose_name='KM Sosire'),
        ),
        migrations.AddField(
            model_name='pontaj',
            name='numar_curse',
            field=models.PositiveIntegerField(default=1, verbose_name='Număr Curse / Notițe traseu'),
        ),
        migrations.AddField(
            model_name='pontaj',
            name='tip_traseu',
            field=models.CharField(choices=[('urban', 'Urban'), ('extraurban', 'Extraurban'), ('mixt', 'Mixt (Urban + Extraurban)')], default='urban', max_length=20, verbose_name='Tip Traseu'),
        ),
    ]
