# Generated by Django 6.0.7 on 2026-07-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontaj_km_plecare_pontaj_km_sosire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileangajat',
            name='rol',
            field=models.CharField(choices=[('angajat', 'Angajat'), ('hr', 'HR / Manager')], default='angajat', max_length=20, verbose_name='Rol'),
        ),
    ]
