# Generated by Django 6.0.7 on 2026-07-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profileangajat_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontaj',
            name='litri_motorina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Litri Motorină Consumați'),
        ),
    ]
