# Generated by Django 6.0.7 on 2026-07-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pontaj_litri_motorina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontaj',
            name='numar_inmatriculare',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Număr Înmatriculare'),
        ),
    ]
