# Generated by Django 6.0.7 on 2026-07-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pontaj_numar_inmatriculare'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileangajat',
            name='adresa',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresă'),
        ),
        migrations.AddField(
            model_name='profileangajat',
            name='cnp',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='CNP'),
        ),
        migrations.AddField(
            model_name='profileangajat',
            name='salariu_baza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salariu de Bază'),
        ),
        migrations.AddField(
            model_name='profileangajat',
            name='tip_contract',
            field=models.CharField(choices=[('determinat', 'Determinat'), ('nedeterminat', 'Nedeterminat')], default='nedeterminat', max_length=20, verbose_name='Tip Contract'),
        ),
    ]
