# Generated by Django 6.0.7 on 2026-07-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profileangajat_adresa_profileangajat_cnp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileangajat',
            name='activ',
            field=models.BooleanField(default=True, verbose_name='Activ'),
        ),
        migrations.AddField(
            model_name='profileangajat',
            name='data_incetare',
            field=models.DateField(blank=True, null=True, verbose_name='Data Încetării Contractului'),
        ),
    ]
