# Generated by Django 6.0.7 on 2026-07-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profileangajat_activ_profileangajat_data_incetare'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileangajat',
            name='zile_concediu_alocate',
            field=models.PositiveIntegerField(default=20, verbose_name='Zile Concediu Alocate/An'),
        ),
    ]
