# Generated by Django 6.0.7 on 2026-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profileangajat_zile_concediu_alocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontaj',
            name='gps_iesire_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pontaj',
            name='gps_iesire_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pontaj',
            name='gps_intrare_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pontaj',
            name='gps_intrare_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pontaj',
            name='poza_iesire',
            field=models.ImageField(blank=True, null=True, upload_to='poze_pontaj/', verbose_name='Poză Ieșire'),
        ),
        migrations.AddField(
            model_name='pontaj',
            name='poza_intrare',
            field=models.ImageField(blank=True, null=True, upload_to='poze_pontaj/', verbose_name='Poză Intrare'),
        ),
    ]
