# Generated by Django 6.0.7 on 2026-08-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pontaj_gps_iesire_lat_pontaj_gps_iesire_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontaj',
            name='gps_iesire_lat',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='gps_iesire_lng',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='gps_intrare_lat',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='gps_intrare_lng',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='km_plecare',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='km_sosire',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='litri_motorina',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='numar_curse',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='numar_inmatriculare',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='ore_lucrate',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='poza_iesire',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='poza_intrare',
        ),
        migrations.RemoveField(
            model_name='pontaj',
            name='tip_traseu',
        ),
    ]
